### ISSUE TITLE
Is it possible to provide some document about how the image is registered?

### ISSUE THREAD

**Issue by ChenXiaoTemp** [yankeppey/PanoramaSample#2]
I found in dbreg.h, it said : 
`
For more technical information on the internal structure of the algorithms used within the db_FrameToRegistration class,
 please follow this <a href="../Sarnoff image registration.docx">link</a>.
`
But I can not found the Sarnoff image registration.docx.

Is it possible to provide some document or paper to describe the algorithm?

**Comment by yankeppey** [comment]
Sorry, what you're referencing to is a part of android sources of some legacy version (2.3 probably?), I don't have any idea of it content. I just combined those android sources into one (hopefully) compilable eclipse project.

**Comment by ChenXiaoTemp** [comment]
I got it, thanks very very much.
